#pragma once

#define VIAL_KEYBOARD_UID {0x49, 0x2E, 0x14, 0xB0, 0x88, 0x6B, 0x1A, 0x0E}
#define VIAL_UNLOCK_COMBO_ROWS {1, 8}
#define VIAL_UNLOCK_COMBO_COLS {0, 7}

#define USE_SERIAL
#define SOFT_SERIAL_PIN D0
#define SPLIT_USB_DETECT
#define SPLIT_HAND_PIN E6

#define WS2812_DI_PIN B7
#define RGBLIGHT_LED_COUNT 87
#define RGBLIGHT_LED_SPLIT {37, 50}
#define RGBLIGHT_SLEEP
#define RGBLIGHT_SPLIT
#define RGBLIGHT_DEFAULT_ON false
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

#define LED_CAPS_LOCK_PIN C7

#define NO_ACTION_ONESHOT
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT
