# 有意義な設定
VIA_ENABLE = yes
VIAL_ENABLE = yes
SPLIT_KEYBOARD = yes
RGBLIGHT_ENABLE = yes

# 不要な機能を無効化
LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
COMBO_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MUSIC_ENABLE = no