VIA_ENABLE = yes
VIAL_ENABLE = yes
MIDI_ENABLE = yes

LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
COMBO_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MUSIC_ENABLE = no